### ISSUE TITLE
Support under Mac OS

### ISSUE THREAD

**Issue by jethrosun** [jart/disaster#12]
It looks like `objdump` is not supported or now replaced as `binutils/gobjdump`. How to make objdump running under Mac OS like the demo does? thx

**Comment by shwsun** [comment]
Looks like I can make disaster running under Mac OS by aliasing. Never mind.

**Comment by alejandroerickson** [comment]
I couldn't figure out how to get emacs to see my aliases except by using a symlink.
`ln -s /opt/local/bin/objdump /opt/local/bin/gobjdump`

**Comment by abougouffa** [comment]
Fixed with c49d5ac86b4bd2a8178ff424aa7df49acec037aa
