### ISSUE TITLE
Can disaster be customized?

### ISSUE THREAD

**Issue by jvillasante** [jart/disaster#16]
I want to read flags from a `.clang_complete` file instead of running `make` on a `Makefile`. Can that be done?. 

Alternatively, is there a way to define flags for disaster on a project basis?

I want to run default `CC` of `C++` with custom flags like: `-std=c++1y O3`

Great Package, BTW!

**Comment by awenocur** [comment]
+1 on the .clang_complete from a frequent irony-mode user; although that would mean explicitly running Clang in cases where it's not the default, such as on nearly anything that's not UNIX.

Maybe a variable that selects Clang could add to the decision tree a search for .clang_complete between the Makefile and running with default options, whereby that variable would be enabled on load if the cc executable were determined to be Clang.

**Comment by abougouffa** [comment]
Since 97bede465c5dd5413821df9503da9203dbb5f771, `disaster` supports CMake via the `compile_commands.json`. 

For tweaking the default flags, you can customize `disaster-cflags` or `disaster-cxxflags`.
