### ISSUE TITLE
Supported file extensions

### ISSUE THREAD

**Issue by 0Tech** [jart/disaster#21]
It checks the file's extension in `disaster`, but the range of supported extensions is narrow.
According to the regular expression in the code, it contains `.c` `.cpp` `.cc`,
but also contains false-positives like `.cp` `.ccp`. I checked these cases with the latest source.
Also it would be great to include extensions `.cxx` `.c++` because `cc-mode` supports these.

**Comment by abougouffa** [comment]
Should be fixed with 4732eec0eb3533d6888d3f028b8a8e30191ff73a
