### ISSUE TITLE
question wrt doom emacs installation instructions 

### ISSUE THREAD

**Issue by soundart** [jart/disaster#28]
Hi,

I tried adding disaster.el to my doom emacs. 

I did the following

In a first try I added only this:
```
(package! disaster
  :recipe (:host github :repo "jart/disaster"))
```
to package.el

An ran "doom sync" 

I then read the rest of the readme and added

```
(use-package! disaster
  :commands (disaster)
  :init
  ;; If you prefer viewing assembly code in `nasm-mode` instead of `asm-mode`
  (setq disaster-assembly-mode 'nasm-mode)

  (map! :localleader
        :map (c++-mode-map c-mode-map fortran-mode-map)
        :desc "Disaster" "d" #'disaster))
```
to config.el and ran "doom sync" again.  

`C-c d` did not work afterwards, but `M-x disaster` showed some activity. However my cmake based project did not compile.

I then found a disaster.el installed in the doom config:

```
$:~/.emacs.d$ fdfind -uuu disaster.el ~/.emacs.d/
/home/frank/.emacs.d/.local/straight/build-28.2/disaster/disaster.el
/home/frank/.emacs.d/.local/straight/build-28.2/disaster/disaster.elc
/home/frank/.emacs.d/.local/straight/repos/disaster/disaster.el
```

Which did not have the date of today. Instead it was from a week (2023-02-07 ) ago. At this date  I probably re-installed/re-compiled doom, but was not aware that disaster.el existed. I do not know why it is in my doom setup. I did not enable it knowingly before today (2023-02-12).

Anyway the problem now is that the code installed is an old release of disaster.el:

```
$ diff -Naur .emacs.d/.local/straight/repos/disaster/disaster.el projects/disaster/disaster.el  | head
--- .emacs.d/.local/straight/repos/disaster/disaster.el	2023-02-07 10:34:37.567169426 +0100
+++ projects/disaster/disaster.el	2023-02-12 10:58:04.009570458 +0100
@@ -1,11 +1,14 @@
-;;; disaster.el --- Disassemble C/C++ code under cursor in Emacs
+;;; disaster.el --- Disassemble C, C++ or Fortran code under cursor -*- lexical-binding: t; -*-
 
-;; Copyright (C) 2013 Justine Tunney.
+;; Copyright (C) 2013-2022 Justine Tunney.
 
 ;; Author: Justine Tunney <jtunney@gmail.com>
```

```
$ git -C ~/.emacs.d/.local/straight/repos/disaster log
commit 10a785facc60d89d78e0d5177985ab1af1741bb4 (grafted, HEAD -> master)
Author: Huang Ying <huang.ying.caritas@gmail.com>
Date:   Tue Oct 17 05:52:38 2017 +0800

    Support separate build root directory (#18)
    
    Many build systems support to use a build root directory that is
    different from the project source code root directory.  This patch is
    to support that.
```
 
Could you please hint howto fix the situation ? Is disaster.el now a default component of doom emacs? 
My doom-emacs n	https://github.com/doomemacs/doomemacs is at commit e96624926d724aff98e862221422cd7124a99c19

```
~/.emacs.d$ rg disaster
bin/doom:68:;;   disasterous side-effects.
modules/lang/cc/packages.el:9:(package! disaster :pin "10a785facc60d89d78e0d5177985ab1af1741bb4")
modules/lang/cc/README.org:36:- [[doom-package:disaster]]
profiles/README.org:43:rollback/snapshot traversal for disaster recovery purposes.
docs/faq.org:92:- No disaster recovery ::
```

However the old version does not seem to work with cmake well...

**Comment by soundart** [comment]
So I think I found way to run the latest disaster.el: I opened it in a buffer and then did eval-region. Afterwards it worked with my cmake based project and showed the disassembly to the left. However the syntax highlighting in the disassembly did not work, it was all gray.

So I think:
- doom emacs uses intentionally and old version of disaster.el
- the installation instructions here do not work  due to this

I will open a doom-emacs issue and ask if it is possible to update disaster.el in  modules/lang/cc/packages.el

**Comment by abougouffa** [comment]
Hello @soundart ,

Thank you for reporting this. In Doom Emacs, I think you can use the `unpin!` macro to force a Doom to use the latest commit. So users facing a similar issue should add this to their `packages.el` file:

```elisp
(unpin! disaster)
```

**Comment by soundart** [comment]
Sorry for not replying. I did not manage to make a doom-emacs issue uptonow as they require a check with latest doom-emacs and I was afraid of messing my setup up. 

With your unpin tip this problem is solved for me.
