### ISSUE TITLE
Disaster is not currently working on all M Mac family

### ISSUE THREAD

**Issue by MacPapo** [jart/disaster#29]
Hi @abougouffa I seen that you are the new maintainer.
I'm trying to run disaster on a M1 Mac and there is no way that I can compile with the current flags.
GCC doesn't support yet the native comp for M chips family, I created a simple patch for this and I would like to create a Pull Request.

**Comment by MacPapo** [comment]
I'm sorry @abougouffa but I can't see them, where can I find them? This is my first PR...

**Comment by abougouffa** [comment]
No problem @MacPapo , congratulations on your first PR!

Code reviews and comments are available in the ["Files changed" section of the PR](https://github.com/jart/disaster/pull/30/files). As in the following figure:

![image](https://user-images.githubusercontent.com/3716399/224403867-370a5baf-a88c-490b-b39f-3126d3a9efcd.png)

**Comment by abougouffa** [comment]
Thanks you for the fix @MacPapo
