### ISSUE TITLE
Couldn’t find corresponding assembly line

### ISSUE THREAD

**Issue by 8dcc** [jart/disaster#31]
Running `M-x disaster` keeps printing the same in all C source files (haven't tried others).

It's using the default `objdump` command:

```bash
objdump -d -M att -Sl --no-show-raw-insn
```

I tried changing mode to `nasm`, tried changing the `objdump` command a bit, but nothing.

Those gray comments that appear on the screenshots are not generated for me, only headers for functions:

![image](https://github.com/jart/disaster/assets/29655971/0d46c5e9-3bc5-4b7a-b956-7866caf6808b)

This is the message log:

```
Running: make -k -C <PATH>/file.o
make: Entering directory '<PATH>'
cc    -c -o file.o file.c
make: Leaving directory '<PATH>'
Running: objdump -d -M att -Sl --no-show-raw-insn <PATH>/file.o
Couldn’t find corresponding assembly line.
```

**Comment by artsi0m** [comment]
Same here

**Comment by 8dcc** [comment]
@artsi0m What distribution are you using? I think the problem is `objdump`, not the Emacs package.

If I run the command shown in `M-x view-echo-area-messages`:

```
objdump -d -M intel -Sl --no-show-raw-insn FILE.o
```

The same output is shown in a terminal.

This is my current `objdump` version, installed from the Arch package manager:

```console
$ objdump --version
GNU objdump (GNU Binutils) 2.43.0
Copyright (C) 2024 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
```

**Comment by artsi0m** [comment]
>What distribution are you using? 

OpenSUSE Tumbleweed.

```shell

lsb_release -a

LSB Version:    n/a
Distributor ID: openSUSE
Description:    openSUSE Tumbleweed
Release:        20240811
Codename:       n/a
```

Command from `M-x echo-area-messages`:
`objdump -d -M att -Sl --no-show-raw-insn FILE.o`
And yeah same output.

objdump version:
`GNU objdump (GNU Binutils; openSUSE Tumbleweed) 2.42.0.20240130-4`

Sorry for late response.

**Comment by 8dcc** [comment]
@artsi0m, I managed to fix it. The problem is that the file isn't getting compiled with debug information.

Setting the following variables managed to fix the issue:
```emacs-lisp
(setq disaster-cflags "-march=native -ggdb3"
      disaster-cxxflags disaster-cflags
      disaster-make-flags "-k CFLAGS=-ggdb3")
```

You can probably use `-g` instead of `-ggdb3`.

---

However, I don't like a couple of things related to this package, and I don't think I will be using it:
- Since I prefer intel syntax and I use `-M intel`, the resulting buffer looks bad with `nasm-mode`, since the output of `objdump` is not meant for this. This is not really this package's fault.
- In my opinion, the way this package handles the compilation is not great in my opinion.

For example, if you have different folders with different Makefiles (e.g. my [scratch](https://github.com/8dcc/scratch) repo), this package will run:

```
make DISASTER-MAKE-FLAGS -C /home/username/PROJECT-ROOT/ RELATIVE/FOLDER/file.o
```

Notice how `PROJECT-ROOT` is not the same folder where `file.o` is. In fact, there is no Makefile in `PROJECT-ROOT` so `make` compiles entirely based on [implicit rules](https://www.gnu.org/software/make/manual/html_node/Implicit-Rules.html). This is even worse news considering that `-g` is not in the default `CFLAGS`. The only way to overwrite this is by adding a `CFLAGS=-g` argument directly to the `make` command. Which is also inconvenient if the Makefile declares its own `CFLAGS` like this:

```Makefile
CFLAGS=-Wall -Wextra
```

Instead of, for example:

```Makefile
CFLAGS+=-Wall -Wextra
```

Sorry for the rant, but I thought it might be useful to somebody.

**Comment by artsi0m** [comment]
Thanks a lot.

I should've guessed this. It is for some extent obvious, that debug option
of compiler should be tried.

I would try with -g option and pull request maybe, as for me, it still
might be necessary to document this in readme.

**Comment by artsi0m** [comment]
> Sorry for the rant

It's OK.

You might also like to try compile-explorer package.
Although I didn't like how it wouldn't load code from file.

There is also rmsbolt and some other packages, that can be found when searching `compiler-explorer language:elisp` on github:

https://github.com/search?q=compiler-explorer+language%3A%22Emacs+Lisp%22+&type=repositories

**Comment by artsi0m** [comment]
![изображение](https://github.com/user-attachments/assets/79a22cde-7022-44c7-811b-5543753b05e5)
```elisp
 (use-package beardbolt
    :load-path "~/.emacs.d/site-lisp/beardbolt")

  (use-package x86-lookup
    :config (setq x86-lookup-pdf "~/Documents/Intel-SDM.pdf")
    :load-path "~/.emacs.d/site-lisp/x86-lookup")
```

[beardbolt](https://github.com/joaotavora/beardbolt),
[x86-lookup](https://github.com/skeeto/x86-lookup)

Seems convenient to me

**Comment by 8dcc** [comment]
@artsi0m, thank you for your recommendations. Beardbolt seems to work pretty nice, I still have to check if it supports Intel syntax.

![screenshot](https://github.com/user-attachments/assets/7eaa9594-d60f-460d-837b-8f67379aef1c)

I did not know about the `x86-lookup` package, but I was very happy to see that the almighty @skeeto wrote it. Up to this point, I have been using [Félix Cloutier's ASM reference](https://www.felixcloutier.com/x86/), but having it integrated in Emacs sounds amazing. Thanks again.

---

As a side note,

> Emacs with C and assembly windows.
> Intel SDM in PDF viewer.
> Torrent and KeePassXC in toolbar.

I salute you, brother 🫡

**Comment by 8dcc** [comment]
Although you can change the assembly syntax with the `beardbolt-asm-syntax`, I made my own fork with some personal changes.

For example, in my fork `bb--asm-mode` derives from `nasm-mode` instead of `asm-mode`, so the syntax highlighting is much better when using `-M intel`:

![image](https://github.com/user-attachments/assets/9956934a-1711-47ec-b68c-1cb77214afb9)

Although I don't know why `objdump` is showing some instructions like:

```nasm
mov	DWORD PTR -48[rbp], eax
```

Instead of:


```nasm
mov	DWORD PTR [rbp-48], eax
```

When using `-M intel`.

I also made some other changes, like using text for the mode names instead of those lightning characters. Change list: [Link](https://github.com/joaotavora/beardbolt/compare/09f7dd86bfaf81ac4ccd51b5cd1b889bb3c5f1aa...8dcc:beardbolt:master)
