### ISSUE TITLE
Support C++11

### ISSUE THREAD

**Issue by PythonNut** [jart/disaster#7]
By passing `-std=c++11` to `c++`. I doubt this will break much, and many people are working with C++11 now.

**Comment by porglezomp** [comment]
If you have a Makefile it should just use that, so this seems unnecessary and incompatible.

**Comment by jart** [comment]
Disaster does support C++11. You can either set your CXXFLAGS environment variable to have that flag. Or you can customize [this emacs variable](https://github.com/jart/disaster/blob/master/disaster.el#L79):

```el
(defcustom disaster-cxxflags (or (getenv "CXXFLAGS")
                                 "-march=native")
  "Command line options to use when compiling C++.!"
  :group 'disaster
  :type 'string)
```

For example:

```el
(setq disaster-cxxflags "-march=native --std=c++11")
```

**Comment by jart** [comment]
But like @porglezomp said, the preferred solution is to have a Makefile. If one of those exist in the directory hierarchy above your file, Disaster will just ask that to build the object file.
